import json
import re

from .launch_configuration import (
    LaunchConfiguration,
    LaunchConfigurationRequest,
    LaunchConfigurationType,
)


class LaunchJSON:
    def __init__(self, launch_json_path: str) -> None:
        self.launch_json_path = launch_json_path
        self.data = None
        self.configurations = dict()

        # the launch json generated by VS Code is malformed for the following reasons
        # // <- comments
        re_remove_comments = re.compile(r"//.*")

        lines = []

        with open(self.launch_json_path) as file:
            for line in file:
                # remove comments
                lines.append(re_remove_comments.sub("", line))

        cleaned_up_json_string = "\n".join(lines)

        self.data = json.loads(cleaned_up_json_string)

        # iterate over configurations
        if "configurations" in self.data.keys():
            for configuration in self.data["configurations"]:
                name = configuration["name"]
                type = LaunchConfigurationType(configuration["type"])
                request = LaunchConfigurationRequest(configuration["request"])
                module = configuration["module"]
                args = configuration["args"]

                self.configurations[name] = LaunchConfiguration(
                    name, type, request, module, args
                )

    def run(self, configuration_name: str) -> None:
        ...
